 # $Id: Makefile,v 1.1.1.1 2007-11-13 12:41:09 krasznaa Exp $
 ###########################################################################
 # @Project: SFrame - ROOT-based analysis framework for ATLAS              #
 # @Package: Plug-ins                                                      #
 #                                                                         #
 # @author Stefan Ask       <Stefan.Ask@cern.ch>           - Manchester    #
 # @author David Berge      <David.Berge@cern.ch>          - CERN          #
 # @author Johannes Haller  <Johannes.Haller@cern.ch>      - Hamburg       #
 # @author Andreas Hoecker  <Andreas.Hocker@cern.ch>       - CERN          #
 # @author A. Krasznahorkay <Attila.Krasznahorkay@cern.ch> - CERN/Debrecen #
 #                                                                         #
 # Makefile compiling the SFramePlugIns library.                           #
 #                                                                         #
 ###########################################################################

# Package information
LIBRARY = SFramePlugIns
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common
