 # $Id$
 ###########################################################################
 # @Project: SFrame - ROOT-based analysis framework for ATLAS              #
 # @Package: User                                                          #
 #                                                                         #
 # @author Stefan Ask       <Stefan.Ask@cern.ch>           - Manchester    #
 # @author David Berge      <David.Berge@cern.ch>          - CERN          #
 # @author Johannes Haller  <Johannes.Haller@cern.ch>      - Hamburg       #
 # @author Andreas Hoecker  <Andreas.Hocker@cern.ch>       - CERN          #
 # @author A. Krasznahorkay <Attila.Krasznahorkay@cern.ch> - CERN/Debrecen #
 #                                                                         #
 # Makefile compiling the SFrameUser library.                              #
 #                                                                         #
 ###########################################################################

# Package information
LIBRARY = SFrameUser
OBJDIR  = obj
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# Include the generic compilation rules
include $(SFRAME_DIR)/Makefile.common
